### ISSUE TITLE
Example on page fails

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-js#24]
Hash: 0c979a907ab8fa6b37dd91574d529819f09d0a77

Source Code:
```
function Main( A,B: array[array[real]];  M,N,L : integer returns array[array[real]] )
  for i in 1, M cross j in 1, L
  returns array of 
      for k in 1, N repeat
	R := A[i,k] * B[k,j]
      returns sum of R 
      end for
  end for
end function
```

Error:
Uncaught TypeError: Cannot read property '0' of undefinedparse @ ir.gen.js:196parseComplex @ ir.gen.js:74parseBody @ ir.gen.js:87parse @ ir.gen.js:165parseComplex @ ir.gen.js:74parseReturns @ ir.gen.js:91parse @ ir.gen.js:166parse @ ir.gen.js:141parse @ ir.gen.js:96node.sisalir @ ir.nodes.js:309trn @ example.html:29onclick @ example.html:98

**Comment by parsifal-47** [comment]
no longer the case,
program is translated to sisal-is:
https://github.com/parsifal-47/sisal-is/blob/master/examples/matmult.sis

GraphML generated:
https://travis-ci.org/parsifal-47/sisal-is/jobs/181082468

**Comment by parsifal-47** [comment]
could I assume these issues as resolved?

**Comment by datsis** [comment]
Is it correct that this repo is no longer supported?
